listen: ":8984"
pkcs11_lib: "/usr/lib/pkcs11/opensc-pkcs11.so"
#pkcs11_lib: "/usr/lib/pkcs11/libIDPrimePKCS11.so"
stamp_background: "./img/stamp_bg.png"
font: "./img/LiberationSans-Regular.ttf"
log_requests: true
